[[headers]]
for = "/"
[headers.values]
Link = '''
</css/main.css>; rel=preload; as=stylesheet, \
</css/hugo-easy-gallery.css>; rel=preload; as=stylesheet, \
</css/ie8.css>; rel=preload; as=stylesheet, \
</js/blazy.min.js>; rel=preload; as=script, \
</js/jquery.min.js>; rel=preload; as=script, \
</js/skel.min.js>; rel=preload; as=script, \
</js/util.js>; rel=preload; as=script, \
</js/main.js>; rel=preload; as=script, \
</images/*.jpg>; rel=preload; as=image, \
</css/images/*.png>; rel=preload; as=image'''
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
[[headers]]
for = "/css/*"
[headers.values]
Cache-Control = "public, max-age=3600000"
[[headers]]
for = "/js/*"
[headers.values]
Cache-Control = "public, max-age=3600000"
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=3600000"